### ISSUE TITLE
UI Bug on Ingredients page

### ISSUE THREAD

**Issue by smuktevi** [smuktevi/recipeat#1]
Issue with error message on updating a wrong ingredient. Failure message on top of the web page displays "ingredient already in bag".
Need to fix in UI.

Also, we may need to ensure that all the other error messages for this page are accurate.

@azhou5211

**Comment by azhou5211** [comment]
Alert messages have been resolves. However, we are successfully updating ingredients that are not in the bag, and successfully deleting ingredients not in the bag. Need BOI to check if the ingredient is in the bag first.
