### ISSUE TITLE
Comparator doesn't work first try

### ISSUE THREAD

**Issue by geiercc** [smuktevi/recipeat#6]
Repro steps:
1. From recipe recommender select two recipes and click compare recipes
2. error occurs

![image](https://user-images.githubusercontent.com/34074212/111016363-4144e580-8362-11eb-8e75-3908467bc9f9.png)

3. click "go back to recipe recommender"
4. Click two recipes to compare
5. Functions as expected

**Comment by geiercc** [comment]
@smuktevi @azhou5211

**Comment by smuktevi** [comment]
We deployed the application with a patch. That should have fixed this bug.
