### ISSUE TITLE
Compare tab doesn't display anything if you click on it

### ISSUE THREAD

**Issue by geiercc** [smuktevi/recipeat#7]
Repro steps:
1. Click on the "Compare!" tab
2. Button to go back to recipe recommender appears
![image](https://user-images.githubusercontent.com/34074212/111016417-bf08f100-8362-11eb-830c-27112b12d77b.png)

Note: Not sure this is an issue just wanted to call this out.

**Comment by geiercc** [comment]
@smuktevi @azhou5211

**Comment by smuktevi** [comment]
Did you include anything to compare before going to the comparator?

**Comment by geiercc** [comment]
@smuktevi No, I didn't - which is why I was thinking this maybe wasn't an issue but just might be a weird user experience.
